export const AUTHORIZATION_START = "AUTHORIZATION_START";
export const AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS";
export const AUTHORIZATION_FAIL = "AUTHORIZATION_FAIL";
export const LOGOUT = "AUTHORIZATION_LOGOUT";

export const FETCH_PROFILE_START = "FETCH_PROFILE_START";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

export const FETCH_SUBREDDIT_START = "FETCH_SUBREDDIT_START";
export const FETCH_SUBREDDIT_SUCCESS = "FETCH_SUBREDDIT_SUCCESS";
export const FETCH_SUBREDDIT_FAIL = "FETCH_SUBREDDIT_FAIL";

// export const FETCH_POSTS_START = "FETCH__POSTS_START";
// export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
// export const FETCH_POSTS_FAIL = "FETCH_POSTS_SUCCESS";
