export const AUTHORIZATION_START = "AUTHORIZATION_START";
export const AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS";
export const AUTHORIZATION_FAIL = "AUTHORIZATION_FAIL";
export const AUTHORIZATION_LOGOUT = "AUTHORIZATION_LOGOUT";

export const FETCH_PROFILE_START = "FETCH_PROFILE_START";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";
